name: Build and deploy tracker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-eidietrich-capitol-tracker-23-processing-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-eidietrich-capitol-tracker-23-processing-
      - name: Install dependencies
        run: npm install
      - name: Refresh inputs
        run: sh refresh-inputs.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: "Automated"
          committer_email: "action@users.noreply.github.com"
          message: "Latest data"
      - name: Push changes
        run: git push
  deploy:
    needs: process
    runs-on: ubuntu-latest
    environment: "MTFP projects"
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            app/public
            app/.cache
            app/node_modules
          key: ${{ runner.os }}-eidietrich-capitol-tracker-23-deploying-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-eidietrich-capitol-tracker-23-deploying-
      - name: Install dependencies
        run: (cd app && npm install)
      - name: Build
        run: (cd app && npm run build)
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Deploy to S3
        run: aws s3 sync app/public s3://apps.montanafreepress.org/capitol-tracker-2023 --delete
      - name: Cache bust
        run: export AWS_PAGER=""; aws cloudfront create-invalidation --distribution-id E3LVPS3XLJHLL5 --paths "/capitol-tracker-2023/*"
      - name: Slack Notification on SUCCESS
        if: success()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_ERIC_TEST_NOTIFICATIONS_WEBHOOK_URL }}
        with:
          text: "Capitol Tracker successfully redeployed"
      - name: Slack Notification on FAIL
        if: failure()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_ERIC_TEST_NOTIFICATIONS_WEBHOOK_URL }}
        with:
          text: "ERROR - something broke with Capitol Tracker deployment"
