name: Build and deploy tracker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-eidietrich-capitol-tracker-23-processing-$${ github.run_id }
          restore-keys: |
            ${{ runner.os }}-eidietrich-capitol-tracker-23-processing-
      - name: Install dependencies
        run: npm install
      - name: Refresh inputs
        run: sh refresh-inputs.sh
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: "Automated"
          committer_email: "action@users.noreply.github.com"
          message: "Latest data"
      - name: Push changes
        run: git push
